#!/usr/bin/env python3
import logging
from librecron.launcher import Launcher

class Config:
    
    active_user_list = None
    daemon_event_log = None
    daemon_event_log_file = None

if __name__ == '__main__':
    
    config = Config()
    logging.basicConfig(level=logging.DEBUG)
    
    config.active_user_list = ['root', 'john-charles']
    config.daemon_event_log = "/var/log/recron/events.log"
    config.daemon_event_log_file = open(config.daemon_event_log, 'wb')
    
    launcher = Launcher(config)
    launcher.start()