#!/usr/bin/env python3

import os
import sys
import logging
from librecron.daemon import RecronDaemon


if __name__ == '__main__':
    
    
    logging.basicConfig(level=logging.DEBUG)
    daemon = RecronDaemon()
    
    if os.getuid() != 0:
            print("Error, this daemon needs to run as root!")
            sys.exit(1)
    
    if sys.argv[1] == 'start':
        daemon.start()
        
    elif sys.argv[1] == 'status':
        if daemon.running():
            print("recron is running...")
        else:
            print("recron is not running.")
            
    elif sys.argv[1] == 'stop':
        daemon.stop()
        
    elif sys.argv[1] == 'restart':
        daemon.restart()

    
    