#!/usr/bin/env python3

import getpass, sys, os
from subprocess import Popen
from librecron.ui import choose_editor, DEFAULT_CRONTAB_TEXT
from librecron.config import CONFIG
from librecron.events import EventList
from colorama import Fore, Back, Style
from colorama import init as coloramainit

class StringBuilder:
    
    chunks = None
    
    def __init__(self):
        self.chunks = []
        
    def append(self, text):
        self.chunks.append(text)
    
    def space(self):
        self.chunks.append(" ")
    
    def do_print(self):
        print("".join(self.chunks))
        
def print_status():
    
    coloramainit(autoreset=True)
    
    event_list = EventList(getpass.getuser())
    
    try:
        event_list.load_events()
    except FileNotFoundError:
        pass
    
    jobs = event_list.get_jobs()
    
    sb = StringBuilder()
    
    sb.append(Style.BRIGHT)
    sb.append(Fore.BLUE)
    
    sb.append("recron")
    sb.space()
    
    sb.append(Style.RESET_ALL)
    
    if len(jobs) == 0:
        sb.append("no jobs have been run for this user yet")
    else:
        sb.append("running %s total jobs" % len(jobs))
    
    sb.do_print()
    
    for job in jobs:
        job_runs, job_health = event_list.get_job_health(job)
        
        sb = StringBuilder()
        sb.append(Style.BRIGHT)
        sb.append("%03s total runs" % job_runs)
        sb.space()
        
        if job_health == 1.0:
            sb.append(Fore.GREEN)
        elif job_health < 1.0 and job_health > 0.8:
            sb.append(Fore.YELLOW)
        elif job_health < 0.8:
            sb.append(Fore.RED)
            
        sb.append("(last 5 runs %03s%% healthy)" % int(job_health * 100))
        sb.space()
        
        sb.append(Style.RESET_ALL)
        sb.append(job)
        
        sb.do_print()
        



def start_editor():
    
    try:
        editor = CONFIG.get_editor()
    except KeyError:
        editor = choose_editor()
        CONFIG.set_editor(editor)
        CONFIG.save()
        
    if not os.path.exists(CONFIG.user_crontab):
        
        with open(CONFIG.user_crontab, 'wb') as crontab_stream:
            crontab_stream.write(DEFAULT_CRONTAB_TEXT.strip().encode("utf-8"))
            
    Popen((editor, CONFIG.user_crontab)).wait()
        
    
    
    


if __name__ == '__main__':
    
    if "-e" in sys.argv:
        start_editor()
    else:
        print_status()
    
    
    
    
