#!/usr/bin/env python3

import os
import sys
import logging
from librecron.daemon import RecronDaemon


if __name__ == '__main__':
    
    
    logging.basicConfig(level=logging.DEBUG)
    
    if os.getuid() != 0:
        print("Error, this daemon needs to run as root!")
        sys.exit(1)
        
    else:
        daemon = RecronDaemon()
        daemon.start()
    
    
    